Make generation of units.ttl comprehensible
OpenManufacturingPlatform/sds-bamm-aspect-meta-model pull request #127
Opened 2022-04-04 07:57 UTC by atextor

Fixes #96. This adds the code to the build process that generates the units.ttl
from the original source. The build target can also be triggered manually using
`./gradlew unitsWriter`, which will download the Excel file from UNECE, run the
RDF generation and write the file to src/main/resources/bamm/unit/2.0.0/units.ttl.

2022-04-08 08:44 UTC, georgschmidtdumont requested changes
Since we now have implemented the unit catalog generation please remove the generated `units.ttl` file from the repo.

2022-04-11 06:34 UTC, atextor commented
@georgschmidtdumont I'm a little torn on this point. Usually you wouldn't check in generated code so I agree with you mentioning this. However there are two reasons I'd still leave the file checked in:
* It allows viewing (and hyperlinking to) the actual unit catalog online. The only alternatives would be (1) downloading and extracting from the jar (2) cloning and building the repo, both of which are not very convenient if you just want to take a look at a unit's definition
* When the UNECE's source file is updated and the locally built units.ttl therefore changes, the resulting diffs will be visible and subsequent commits/PRs capture these changes. The PR itself can be viewed and linked to.

What do you think?

2022-04-11 13:20 UTC, georgschmidtdumont commented
Hi @atextor ,

we can keep the generated code in this case.

2022-04-11 13:20 UTC, georgschmidtdumont approved these changes

2022-04-12 07:55 UTC, merged